# Generated by Django 6.0.7 on 2026-09-02 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interviews', '0002_aiinterviewsession_aiquestion_aianswer_calllog'),
        ('jobs', '0004_job_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('category', models.CharField(choices=[('INTRODUCTION', 'Introduction'), ('EXPERIENCE', 'Experience'), ('SKILLS', 'Skills'), ('AVAILABILITY', 'Availability'), ('SALARY', 'Salary')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_questions', to='jobs.job')),
                ('question_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_questions', to='ai_interviews.questiontemplate')),
            ],
        ),
    ]
