# Generated by Django 6.0.7 on 2026-09-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interviews', '0003_questiontemplate_jobquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiinterviewsession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aiinterviewsession',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='aiinterviewsession',
            name='current_question_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiinterviewsession',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
    ]
