# Generated by Django 6.0.7 on 2026-09-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interviews', '0004_remove_aiinterviewsession_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontemplate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='questiontemplate',
            name='is_active',
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='follow_up_question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
