# Generated by Django 6.0.7 on 2026-09-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interviews', '0005_remove_questiontemplate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontemplate',
            name='follow_up_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
