# Generated by Django 6.0.7 on 2026-09-02 19:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interviews', '0006_questiontemplate_follow_up_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterviewsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiinterviewsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
