# Generated by Django 6.0.7 on 2026-09-03 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interviews', '0007_aiinterviewsession_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnswerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=0)),
                ('completeness_score', models.FloatField(default=0)),
                ('keyword_score', models.FloatField(default=0)),
                ('final_score', models.FloatField(default=0)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('ai_annotation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='ai_interviews.aianswer')),
            ],
        ),
    ]
