# Generated by Django 6.0.7 on 2026-09-05 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interviews', '0009_availabilityslot_interviewschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reminder_type', models.CharField(choices=[('FIRST_REMINDER', 'First Reminder'), ('SECOND_REMINDER', 'Second Reminder'), ('FINAL_REMINDER', 'Final Reminder')], max_length=30)),
                ('minutes_before', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='ai_interviews.interviewschedule')),
                ('reminder_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='ai_interviews.reminderrule')),
            ],
        ),
    ]
