# Generated by Django 6.0.7 on 2026-09-07 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interviews', '0010_reminderrule_reminderlog'),
        ('applications', '0005_delete_aicall'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICandidateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_score', models.FloatField(default=0)),
                ('ai_call_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('strengths', models.JSONField(default=list)),
                ('risks', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_report', to='applications.jobapplication')),
            ],
        ),
    ]
