# Generated by Django 6.0.7 on 2026-08-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_jobapplication_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ats_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
