# Generated by Django 6.0.7 on 2026-08-31 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_aicall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AICall',
        ),
    ]
