# Generated by Django 6.0.7 on 2026-09-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_delete_aicall'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=set(),
        ),
    ]
