SKILLS = [
    "Python",
    "Django",
    "Django REST Framework",
    "FastAPI",
    "REST APIs",
    "SQL",
    "PostgreSQL",
    "MySQL",
    "SQLite",
    "JavaScript",
    "React",
    "HTML",
    "CSS",
    "Bootstrap",
    "Git",
    "GitHub",
    "Docker",
    "AWS",
    "LangGraph",
    "Machine Learning",
    "Data Science",
]
