# Generated by Django 6.0.7 on 2026-07-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_candidateprofile_employerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CandidateProfile',
        ),
        migrations.DeleteModel(
            name='EmployerProfile',
        ),
    ]
